# Generated by Django 3.0.8 on 2020-07-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.TextField(max_length=100)),
                ('title', models.TextField(max_length=100)),
                ('subject', models.TextField(max_length=500)),
            ],
        ),
    ]
