# Generated by Django 3.0.8 on 2020-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='myportfolio/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
